import React from 'react';
import { useAuth } from '../../context/AuthContext';
import { useAQARReports } from '../../hooks/useAQARReports';
import { AQARStatusBadge } from '../../components/aqar/AQARStatusBadge';
import { Loader } from '../../components/common/Loader';
import { Card } from '../../components/common/Card';
import { ArrowLeft, History, Eye, Download } from 'lucide-react';
import { Link } from 'react-router-dom';

export const AQARHistory = () => {
  const { user } = useAuth();
  const { reports, loading } = useAQARReports();

  if (loading) {
    return <Loader message="Loading AQAR Report Version History..." />;
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-200/80">
        <div className="flex items-center gap-3">
          <Link
            to="/aqar"
            className="p-2 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 transition"
          >
            <ArrowLeft className="w-4 h-4" />
          </Link>
          <div>
            <h1 className="text-xl sm:text-2xl font-black text-slate-900 tracking-tight">
              AQAR Report Version History & Snapshot Archive
            </h1>
            <p className="text-xs text-slate-500 font-medium mt-0.5">
              Immutable version history, draft iterations & finalized annual report snapshots across academic years
            </p>
          </div>
        </div>
      </div>

      <Card className="p-4 sm:p-6 space-y-4">
        <div className="overflow-x-auto rounded-xl border border-slate-200 custom-scroll text-xs">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-slate-50 text-slate-700 border-b font-bold uppercase tracking-wider">
                <th className="p-3">Report ID</th>
                <th className="p-3">Academic Year</th>
                <th className="p-3 text-center">Version</th>
                <th className="p-3 text-center">Status</th>
                <th className="p-3">Generated By</th>
                <th className="p-3 text-center">Finalized Date</th>
                <th className="p-3 text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 font-medium">
              {reports.map((r) => (
                <tr key={r.id} className="hover:bg-slate-50/80 transition-colors">
                  <td className="p-3 font-extrabold text-indigo-900">{r.reportId}</td>
                  <td className="p-3 font-bold text-slate-900">{r.academicYear}</td>
                  <td className="p-3 text-center font-bold text-slate-800">v{r.version}</td>
                  <td className="p-3 text-center">
                    <AQARStatusBadge status={r.status} />
                  </td>
                  <td className="p-3 text-slate-700">{r.generatedBy}</td>
                  <td className="p-3 text-center font-bold text-slate-800">{r.finalizedAt || '—'}</td>
                  <td className="p-3 text-right whitespace-nowrap">
                    <Link
                      to={`/aqar/${r.id}/preview`}
                      className="inline-flex items-center gap-1 text-indigo-600 hover:text-indigo-800 font-bold text-xs bg-indigo-50 hover:bg-indigo-100 px-2.5 py-1.5 rounded-lg transition"
                    >
                      <Eye className="w-3.5 h-3.5" />
                      <span>Preview Snapshot</span>
                    </Link>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
};
