// Configurable Representative NAAC Criteria 1–7 Metrics Catalog (Stage 5G)

import { METRIC_TYPES, METRIC_READINESS_STATUS } from './accreditationFrameworkConfig';

export const REQUISITE_NAAC_METRICS = [
  // --- CRITERION 1: Curricular Aspects ---
  {
    id: 'NAAC-C1-M1',
    criterionId: 'NAAC-C1',
    code: '1.1.1',
    name: 'Curricula Revision & Syllabus Upgrade Percentage',
    description: 'Percentage of programs where syllabus revision was carried out during the last academic year.',
    type: METRIC_TYPES.QUANTITATIVE,
    frequency: 'ANNUAL',
    applicableScope: 'INSTITUTION',
    required: true,
    target: 100,
    unit: 'PERCENTAGE',
    dataSources: ['ACADEMIC', 'DEPARTMENT'],
    requiredEvidenceTypes: ['CURRICULUM_DOC', 'BOS_MINUTES'],
    responsibleRoles: ['IQAC_HEAD', 'DEAN'],
    enabled: true,
  },
  {
    id: 'NAAC-C1-M2',
    criterionId: 'NAAC-C1',
    code: '1.2.1',
    name: 'Academic Flexibility & Elective Course Choice',
    description: 'Percentage of new courses introduced across all programs offering elective choices.',
    type: METRIC_TYPES.QUANTITATIVE,
    frequency: 'ANNUAL',
    applicableScope: 'INSTITUTION',
    required: true,
    target: 80,
    unit: 'PERCENTAGE',
    dataSources: ['ACADEMIC'],
    requiredEvidenceTypes: ['SYLLABUS_COPY'],
    responsibleRoles: ['DEAN', 'HOD'],
    enabled: true,
  },
  {
    id: 'NAAC-C1-M3',
    criterionId: 'NAAC-C1',
    code: '1.4.1',
    name: 'Structured Stakeholder Feedback Collection & Action Taken',
    description: 'Structured feedback obtained on curriculum from Students, Teachers, Employers & Alumni.',
    type: METRIC_TYPES.COMPOSITE,
    frequency: 'SEMESTER',
    applicableScope: 'INSTITUTION',
    required: true,
    target: 90,
    unit: 'PERCENTAGE',
    dataSources: ['FEEDBACK', 'QUALITY_INDICATOR'],
    requiredEvidenceTypes: ['FEEDBACK_ANALYSIS_REPORT', 'ACTION_TAKEN_REPORT'],
    responsibleRoles: ['IQAC_COORDINATOR', 'HOD'],
    enabled: true,
  },

  // --- CRITERION 2: Teaching-Learning and Evaluation ---
  {
    id: 'NAAC-C2-M1',
    criterionId: 'NAAC-C2',
    code: '2.1.1',
    name: 'Average Enrolment Percentage',
    description: 'Ratio of students enrolled vs total sanctioned intake capacity.',
    type: METRIC_TYPES.QUANTITATIVE,
    frequency: 'ANNUAL',
    applicableScope: 'INSTITUTION',
    required: true,
    target: 95,
    unit: 'PERCENTAGE',
    dataSources: ['STUDENT'],
    requiredEvidenceTypes: ['ENROLMENT_LIST'],
    responsibleRoles: ['DEAN', 'HOD'],
    enabled: true,
  },
  {
    id: 'NAAC-C2-M2',
    criterionId: 'NAAC-C2',
    code: '2.4.1',
    name: 'Full-Time Faculty holding Ph.D. Qualification',
    description: 'Percentage of full-time teachers with Ph.D. degrees.',
    type: METRIC_TYPES.QUANTITATIVE,
    frequency: 'ANNUAL',
    applicableScope: 'DEPARTMENT',
    required: true,
    target: 85,
    unit: 'PERCENTAGE',
    dataSources: ['FACULTY', 'QUALITY_INDICATOR'],
    requiredEvidenceTypes: ['DEGREE_CERTIFICATE'],
    responsibleRoles: ['IQAC_HEAD', 'HOD'],
    enabled: true,
  },

  // --- CRITERION 3: Research, Innovations and Extension ---
  {
    id: 'NAAC-C3-M1',
    criterionId: 'NAAC-C3',
    code: '3.1.1',
    name: 'Extramural Funded Research Grants Received (INR Lakhs)',
    description: 'Grants received from government and non-governmental agencies for research projects.',
    type: METRIC_TYPES.QUANTITATIVE,
    frequency: 'ANNUAL',
    applicableScope: 'INSTITUTION',
    required: true,
    target: 150,
    unit: 'CURRENCY',
    dataSources: ['RESEARCH', 'SUBMISSION'],
    requiredEvidenceTypes: ['SANCTION_LETTER', 'UTILIZATION_CERTIFICATE'],
    responsibleRoles: ['IQAC_HEAD', 'IQAC_COORDINATOR'],
    enabled: true,
  },
  {
    id: 'NAAC-C3-M2',
    criterionId: 'NAAC-C3',
    code: '3.3.1',
    name: 'Scopus / SCI Journal Publications per Faculty',
    description: 'Number of research papers published per teacher in Scopus/SCI indexed journals.',
    type: METRIC_TYPES.EVIDENCE_BASED,
    frequency: 'ANNUAL',
    applicableScope: 'DEPARTMENT',
    required: true,
    target: 1.5,
    unit: 'RATIO',
    dataSources: ['PUBLICATION', 'EVIDENCE', 'QUALITY_INDICATOR'],
    requiredEvidenceTypes: ['PUBLICATION_PROOF', 'DOI_LANDING_PAGE'],
    responsibleRoles: ['IQAC_COORDINATOR', 'STAFF'],
    enabled: true,
  },
  {
    id: 'NAAC-C3-M3',
    criterionId: 'NAAC-C3',
    code: '3.4.1',
    name: 'Patents Published & Granted Count',
    description: 'Total number of intellectual property patents published and granted during the year.',
    type: METRIC_TYPES.QUANTITATIVE,
    frequency: 'ANNUAL',
    applicableScope: 'INSTITUTION',
    required: true,
    target: 20,
    unit: 'COUNT',
    dataSources: ['PATENT', 'SUBMISSION'],
    requiredEvidenceTypes: ['PATENT_CERTIFICATE', 'GAZETTE_PROOF'],
    responsibleRoles: ['IQAC_HEAD', 'HOD'],
    enabled: true,
  },

  // --- CRITERION 4: Infrastructure and Learning Resources ---
  {
    id: 'NAAC-C4-M1',
    criterionId: 'NAAC-C4',
    code: '4.1.1',
    name: 'Percentage of ICT-Enabled Classrooms & Seminar Halls',
    description: 'Classrooms and seminar halls equipped with ICT infrastructure and smart boards.',
    type: METRIC_TYPES.QUANTITATIVE,
    frequency: 'ANNUAL',
    applicableScope: 'INSTITUTION',
    required: true,
    target: 100,
    unit: 'PERCENTAGE',
    dataSources: ['INSTITUTION'],
    requiredEvidenceTypes: ['GEO_TAGGED_PHOTOS', 'STOCK_REGISTER'],
    responsibleRoles: ['DEAN', 'HOD'],
    enabled: true,
  },

  // --- CRITERION 5: Student Support and Progression ---
  {
    id: 'NAAC-C5-M1',
    criterionId: 'NAAC-C5',
    code: '5.1.1',
    name: 'Student Placement & Higher Education Progression Rate',
    description: 'Percentage of graduating students placed or progressing to higher education.',
    type: METRIC_TYPES.QUANTITATIVE,
    frequency: 'ANNUAL',
    applicableScope: 'DEPARTMENT',
    required: true,
    target: 85,
    unit: 'PERCENTAGE',
    dataSources: ['PLACEMENT', 'STUDENT'],
    requiredEvidenceTypes: ['OFFER_LETTERS', 'ADMISSION_PROOFS'],
    responsibleRoles: ['HOD', 'IQAC_COORDINATOR'],
    enabled: true,
  },

  // --- CRITERION 6: Governance, Leadership and Management ---
  {
    id: 'NAAC-C6-M1',
    criterionId: 'NAAC-C6',
    code: '6.3.1',
    name: 'Faculty 5-Day ATAL / NPTEL FDP Training Completion',
    description: 'Percentage of teachers participating in professional development programs.',
    type: METRIC_TYPES.COMPLIANCE,
    frequency: 'ANNUAL',
    applicableScope: 'DEPARTMENT',
    required: true,
    target: 90,
    unit: 'PERCENTAGE',
    dataSources: ['COMPLIANCE', 'ACTIVITY', 'QUALITY_INDICATOR'],
    requiredEvidenceTypes: ['FDP_CERTIFICATE'],
    responsibleRoles: ['IQAC_COORDINATOR', 'HOD'],
    enabled: true,
  },
  {
    id: 'NAAC-C6-M2',
    criterionId: 'NAAC-C6',
    code: '6.5.1',
    name: 'IQAC Meeting Frequency & Finalized Minutes Resolution Rate',
    description: 'Regular IQAC Board reviews, finalized minutes of meetings, and action item closure.',
    type: METRIC_TYPES.DOCUMENTARY,
    frequency: 'QUARTERLY',
    applicableScope: 'INSTITUTION',
    required: true,
    target: 100,
    unit: 'PERCENTAGE',
    dataSources: ['MEETING', 'ACTION_ITEM'],
    requiredEvidenceTypes: ['MINUTES_OF_MEETING', 'ACTION_TAKEN_REPORT'],
    responsibleRoles: ['IQAC_HEAD'],
    enabled: true,
  },

  // --- CRITERION 7: Institutional Values and Best Practices ---
  {
    id: 'NAAC-C7-M1',
    criterionId: 'NAAC-C7',
    code: '7.1.1',
    name: 'Green Audit, Solar Energy & Waste Management Compliance',
    description: 'Environmental quality audits, solar power generation, and waste management practices.',
    type: METRIC_TYPES.QUALITATIVE,
    frequency: 'ANNUAL',
    applicableScope: 'INSTITUTION',
    required: true,
    target: 100,
    unit: 'PERCENTAGE',
    dataSources: ['COMPLIANCE', 'MANUAL_ENTRY'],
    requiredEvidenceTypes: ['GREEN_AUDIT_REPORT', 'ENERGY_AUDIT_REPORT'],
    responsibleRoles: ['IQAC_HEAD'],
    enabled: true,
  },
];
