// Centralized Institutional Compliance Configuration (Stage 5F)

export const COMPLIANCE_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  IN_PROGRESS: 'IN_PROGRESS',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  COMPLIANT: 'COMPLIANT',
  PARTIALLY_COMPLIANT: 'PARTIALLY_COMPLIANT',
  NON_COMPLIANT: 'NON_COMPLIANT',
  OVERDUE: 'OVERDUE',
  NOT_APPLICABLE: 'NOT_APPLICABLE',
};

export const COMPLIANCE_STATUS_CONFIG = {
  COMPLIANT: {
    label: 'COMPLIANT',
    classes: 'bg-emerald-50 text-emerald-800 border-emerald-300 font-extrabold shadow-2xs',
    dot: 'bg-emerald-500',
  },
  PARTIALLY_COMPLIANT: {
    label: 'PARTIALLY COMPLIANT',
    classes: 'bg-blue-50 text-blue-800 border-blue-200 font-bold',
    dot: 'bg-blue-500',
  },
  IN_PROGRESS: {
    label: 'IN PROGRESS',
    classes: 'bg-indigo-50 text-indigo-700 border-indigo-200',
    dot: 'bg-indigo-500',
  },
  SUBMITTED: {
    label: 'SUBMITTED',
    classes: 'bg-violet-50 text-violet-700 border-violet-200',
    dot: 'bg-violet-500',
  },
  UNDER_REVIEW: {
    label: 'UNDER REVIEW',
    classes: 'bg-violet-50 text-violet-700 border-violet-200',
    dot: 'bg-violet-500',
  },
  NON_COMPLIANT: {
    label: 'NON COMPLIANT',
    classes: 'bg-rose-50 text-rose-800 border-rose-300 font-extrabold',
    dot: 'bg-rose-500',
  },
  OVERDUE: {
    label: 'OVERDUE',
    classes: 'bg-rose-100 text-rose-900 border-rose-300 font-black',
    dot: 'bg-rose-600',
  },
  NOT_STARTED: {
    label: 'NOT STARTED',
    classes: 'bg-slate-100 text-slate-700 border-slate-200',
    dot: 'bg-slate-400',
  },
  NOT_APPLICABLE: {
    label: 'N/A',
    classes: 'bg-slate-100 text-slate-500 border-slate-200',
    dot: 'bg-slate-400',
  },
};

export const COMPLIANCE_REQUIREMENTS = [
  {
    id: 'COMP-DEPT-001',
    code: 'C-001',
    name: 'Annual Department Quality & Compliance Report',
    description: 'Each department must submit a verified annual quality compliance report.',
    category: 'DOCUMENTATION',
    frequency: 'ANNUAL',
    applicableScope: 'DEPARTMENT',
    required: true,
    target: 100,
    dueDateRule: 'ACADEMIC_YEAR_END',
    evidenceRequired: true,
    verificationRequired: true,
    sourceType: 'DEPARTMENT_REPORT',
    enabled: true,
  },
  {
    id: 'COMP-FAC-001',
    code: 'C-002',
    name: 'Faculty Profile & Qualification Documentation',
    description: '100% verified Ph.D. degree & appointment evidence documentation.',
    category: 'FACULTY',
    frequency: 'ANNUAL',
    applicableScope: 'DEPARTMENT',
    required: true,
    target: 100,
    dueDateRule: 'SEMESTER_START',
    evidenceRequired: true,
    verificationRequired: true,
    sourceType: 'FACULTY_PROFILE',
    enabled: true,
  },
  {
    id: 'COMP-RES-001',
    code: 'C-003',
    name: 'Scopus / SCI Research Publication Proof Verification',
    description: 'Attach verified Scopus DOI landing page proof for all claimed publications.',
    category: 'RESEARCH',
    frequency: 'QUARTERLY',
    applicableScope: 'DEPARTMENT',
    required: true,
    target: 90,
    dueDateRule: 'QUARTERLY_END',
    evidenceRequired: true,
    verificationRequired: true,
    sourceType: 'PUBLICATION',
    enabled: true,
  },
  {
    id: 'COMP-FDP-001',
    code: 'C-004',
    name: 'Faculty 5-Day ATAL / NPTEL FDP Training',
    description: 'Minimum 90% department faculty members must complete 5-day accredited FDP.',
    category: 'TRAINING',
    frequency: 'ANNUAL',
    applicableScope: 'DEPARTMENT',
    required: true,
    target: 90,
    dueDateRule: 'ACADEMIC_YEAR_END',
    evidenceRequired: true,
    verificationRequired: true,
    sourceType: 'FDP_TRAINING',
    enabled: true,
  },
  {
    id: 'COMP-ACT-001',
    code: 'C-005',
    name: 'IQAC Resolution Action Item Resolution',
    description: 'Closure of all assigned meeting resolution action items before due dates.',
    category: 'OPERATIONS',
    frequency: 'QUARTERLY',
    applicableScope: 'DEPARTMENT',
    required: true,
    target: 85,
    dueDateRule: 'ACTION_DUE_DATE',
    evidenceRequired: false,
    verificationRequired: false,
    sourceType: 'ACTION_ITEM',
    enabled: true,
  },
];
