// Department Portal role configuration (Stage 7).
// Single source of truth for HOD vs IQAC Coordinator modules and permissions.
// Pages and layout must consume these helpers instead of scattering role checks.

import { ROLES } from './roles';
import { PERMISSIONS } from './permissions';

// Stage 7 department-scoped permission vocabulary. Each entry maps to the
// closest existing institutional permission so centralized RBAC keeps working
// while department UI code uses DEPARTMENT_* names.
export const DEPARTMENT_PERMISSIONS = {
  DEPARTMENT_DASHBOARD_VIEW: 'DEPARTMENT_DASHBOARD_VIEW',

  DEPARTMENT_STAFF_VIEW: 'DEPARTMENT_STAFF_VIEW',
  DEPARTMENT_STAFF_DETAILS_VIEW: 'DEPARTMENT_STAFF_DETAILS_VIEW',

  DEPARTMENT_SUBMISSION_VIEW: 'DEPARTMENT_SUBMISSION_VIEW',
  DEPARTMENT_SUBMISSION_REVIEW: 'DEPARTMENT_SUBMISSION_REVIEW',
  DEPARTMENT_SUBMISSION_APPROVE: 'DEPARTMENT_SUBMISSION_APPROVE',
  DEPARTMENT_SUBMISSION_RETURN: 'DEPARTMENT_SUBMISSION_RETURN',
  DEPARTMENT_SUBMISSION_REJECT: 'DEPARTMENT_SUBMISSION_REJECT',
  DEPARTMENT_SUBMISSION_COMMENT: 'DEPARTMENT_SUBMISSION_COMMENT',

  DEPARTMENT_EVIDENCE_VIEW: 'DEPARTMENT_EVIDENCE_VIEW',
  DEPARTMENT_EVIDENCE_REVIEW: 'DEPARTMENT_EVIDENCE_REVIEW',
  DEPARTMENT_EVIDENCE_RETURN: 'DEPARTMENT_EVIDENCE_RETURN',
  DEPARTMENT_EVIDENCE_COMMENT: 'DEPARTMENT_EVIDENCE_COMMENT',

  DEPARTMENT_ACTIVITY_VIEW: 'DEPARTMENT_ACTIVITY_VIEW',
  DEPARTMENT_ACTIVITY_CREATE: 'DEPARTMENT_ACTIVITY_CREATE',
  DEPARTMENT_ACTIVITY_EDIT: 'DEPARTMENT_ACTIVITY_EDIT',
  DEPARTMENT_ACTIVITY_ASSIGN: 'DEPARTMENT_ACTIVITY_ASSIGN',

  DEPARTMENT_MEETING_VIEW: 'DEPARTMENT_MEETING_VIEW',
  DEPARTMENT_MEETING_CREATE: 'DEPARTMENT_MEETING_CREATE',
  DEPARTMENT_MEETING_EDIT: 'DEPARTMENT_MEETING_EDIT',
  DEPARTMENT_MEETING_MANAGE_AGENDA: 'DEPARTMENT_MEETING_MANAGE_AGENDA',
  DEPARTMENT_MEETING_MANAGE_MINUTES: 'DEPARTMENT_MEETING_MANAGE_MINUTES',

  DEPARTMENT_ACTION_VIEW: 'DEPARTMENT_ACTION_VIEW',
  DEPARTMENT_ACTION_ASSIGN: 'DEPARTMENT_ACTION_ASSIGN',
  DEPARTMENT_ACTION_UPDATE: 'DEPARTMENT_ACTION_UPDATE',

  DEPARTMENT_QUALITY_VIEW: 'DEPARTMENT_QUALITY_VIEW',
  DEPARTMENT_COMPLIANCE_VIEW: 'DEPARTMENT_COMPLIANCE_VIEW',
  DEPARTMENT_COMPLIANCE_UPDATE: 'DEPARTMENT_COMPLIANCE_UPDATE',

  DEPARTMENT_ACCREDITATION_VIEW: 'DEPARTMENT_ACCREDITATION_VIEW',
  DEPARTMENT_ACCREDITATION_UPDATE: 'DEPARTMENT_ACCREDITATION_UPDATE',

  DEPARTMENT_IMPROVEMENT_VIEW: 'DEPARTMENT_IMPROVEMENT_VIEW',
  DEPARTMENT_IMPROVEMENT_UPDATE: 'DEPARTMENT_IMPROVEMENT_UPDATE',

  DEPARTMENT_NOTIFICATION_SEND: 'DEPARTMENT_NOTIFICATION_SEND',
};

// Fallback mapping: DEPARTMENT_* -> institutional PERMISSIONS equivalent.
// Used when the authenticated user only carries institutional permissions.
export const DEPARTMENT_PERMISSION_FALLBACK = {
  DEPARTMENT_DASHBOARD_VIEW: PERMISSIONS.IQAC_DASHBOARD_VIEW,
  DEPARTMENT_STAFF_VIEW: PERMISSIONS.STAFF_PROFILE_VIEW,
  DEPARTMENT_STAFF_DETAILS_VIEW: PERMISSIONS.STAFF_PROFILE_VIEW,
  DEPARTMENT_SUBMISSION_VIEW: PERMISSIONS.SUBMISSION_VIEW,
  DEPARTMENT_SUBMISSION_REVIEW: PERMISSIONS.SUBMISSION_REVIEW,
  DEPARTMENT_SUBMISSION_APPROVE: PERMISSIONS.SUBMISSION_APPROVE,
  DEPARTMENT_SUBMISSION_RETURN: PERMISSIONS.SUBMISSION_RETURN,
  DEPARTMENT_SUBMISSION_REJECT: PERMISSIONS.SUBMISSION_REJECT,
  DEPARTMENT_SUBMISSION_COMMENT: PERMISSIONS.SUBMISSION_COMMENT,
  DEPARTMENT_EVIDENCE_VIEW: PERMISSIONS.EVIDENCE_VIEW,
  DEPARTMENT_EVIDENCE_REVIEW: PERMISSIONS.EVIDENCE_REVIEW,
  DEPARTMENT_EVIDENCE_RETURN: PERMISSIONS.EVIDENCE_RETURN,
  DEPARTMENT_EVIDENCE_COMMENT: PERMISSIONS.EVIDENCE_HISTORY_VIEW,
  DEPARTMENT_ACTIVITY_VIEW: PERMISSIONS.ACTIVITY_VIEW,
  DEPARTMENT_ACTIVITY_CREATE: PERMISSIONS.ACTIVITY_CREATE,
  DEPARTMENT_ACTIVITY_EDIT: PERMISSIONS.ACTIVITY_EDIT,
  DEPARTMENT_ACTIVITY_ASSIGN: PERMISSIONS.ACTIVITY_UPDATE,
  DEPARTMENT_MEETING_VIEW: PERMISSIONS.MEETING_VIEW,
  DEPARTMENT_MEETING_CREATE: PERMISSIONS.MEETING_CREATE,
  DEPARTMENT_MEETING_EDIT: PERMISSIONS.MEETING_EDIT,
  DEPARTMENT_MEETING_MANAGE_AGENDA: PERMISSIONS.AGENDA_CREATE,
  DEPARTMENT_MEETING_MANAGE_MINUTES: PERMISSIONS.MINUTES_CREATE,
  DEPARTMENT_ACTION_VIEW: PERMISSIONS.ACTION_ITEM_VIEW,
  DEPARTMENT_ACTION_ASSIGN: PERMISSIONS.ACTION_ITEM_ASSIGN,
  DEPARTMENT_ACTION_UPDATE: PERMISSIONS.ACTION_ITEM_UPDATE,
  DEPARTMENT_QUALITY_VIEW: PERMISSIONS.QUALITY_VIEW,
  DEPARTMENT_COMPLIANCE_VIEW: PERMISSIONS.COMPLIANCE_VIEW,
  DEPARTMENT_COMPLIANCE_UPDATE: PERMISSIONS.COMPLIANCE_UPDATE,
  DEPARTMENT_ACCREDITATION_VIEW: PERMISSIONS.ACCREDITATION_VIEW,
  DEPARTMENT_ACCREDITATION_UPDATE: PERMISSIONS.ACCREDITATION_GAP_VIEW,
  DEPARTMENT_IMPROVEMENT_VIEW: PERMISSIONS.IMPROVEMENT_PLAN_VIEW,
  DEPARTMENT_IMPROVEMENT_UPDATE: PERMISSIONS.IMPROVEMENT_PLAN_EDIT,
  DEPARTMENT_NOTIFICATION_SEND: PERMISSIONS.IQAC_COORDINATOR_NOTIFICATION_SEND,
};

const DP = DEPARTMENT_PERMISSIONS;

export const DEPARTMENT_MODULES = [
  { id: 'dashboard', label: 'Dashboard', path: '/department', icon: 'LayoutDashboard', permission: DP.DEPARTMENT_DASHBOARD_VIEW, exact: true },
  { id: 'staff', label: 'Staff', path: '/department/staff', icon: 'Users', permission: DP.DEPARTMENT_STAFF_VIEW },
  { id: 'review', label: 'Review', path: '/department/review', icon: 'ClipboardCheck', permission: DP.DEPARTMENT_SUBMISSION_VIEW },
  { id: 'evidence', label: 'Evidence', path: '/department/evidence', icon: 'FolderCheck', permission: DP.DEPARTMENT_EVIDENCE_VIEW },
  { id: 'activities', label: 'Activities', path: '/department/activities', icon: 'Sparkles', permission: DP.DEPARTMENT_ACTIVITY_VIEW },
  { id: 'meetings', label: 'Meetings', path: '/department/meetings', icon: 'CalendarDays', permission: DP.DEPARTMENT_MEETING_VIEW },
  { id: 'actions', label: 'Action Items', path: '/department/action-items', icon: 'CheckSquare', permission: DP.DEPARTMENT_ACTION_VIEW },
  { id: 'quality', label: 'Quality', path: '/department/quality', icon: 'Star', permission: DP.DEPARTMENT_QUALITY_VIEW },
  { id: 'compliance', label: 'Compliance', path: '/department/compliance', icon: 'ShieldCheck', permission: DP.DEPARTMENT_COMPLIANCE_VIEW },
  { id: 'accreditation', label: 'Accreditation', path: '/department/accreditation', icon: 'Award', permission: DP.DEPARTMENT_ACCREDITATION_VIEW },
  { id: 'improvement', label: 'Improvement Plans', path: '/department/improvement-plans', icon: 'TrendingUp', permission: DP.DEPARTMENT_IMPROVEMENT_VIEW },
  { id: 'notifications', label: 'Notifications', path: '/department/notifications', icon: 'Bell', permission: DP.DEPARTMENT_NOTIFICATION_SEND },
];

export const DEPARTMENT_PORTAL_CONFIG = {
  [ROLES.HOD]: {
    label: 'HOD',
    modules: ['dashboard', 'staff', 'review', 'evidence', 'activities', 'meetings', 'actions', 'quality', 'compliance', 'accreditation', 'notifications'],
    permissions: [
      DP.DEPARTMENT_DASHBOARD_VIEW,
      DP.DEPARTMENT_STAFF_VIEW,
      DP.DEPARTMENT_STAFF_DETAILS_VIEW,
      DP.DEPARTMENT_SUBMISSION_VIEW,
      DP.DEPARTMENT_SUBMISSION_REVIEW,
      DP.DEPARTMENT_SUBMISSION_APPROVE,
      DP.DEPARTMENT_SUBMISSION_RETURN,
      DP.DEPARTMENT_SUBMISSION_REJECT,
      DP.DEPARTMENT_SUBMISSION_COMMENT,
      DP.DEPARTMENT_EVIDENCE_VIEW,
      DP.DEPARTMENT_EVIDENCE_REVIEW,
      DP.DEPARTMENT_EVIDENCE_COMMENT,
      DP.DEPARTMENT_ACTIVITY_VIEW,
      DP.DEPARTMENT_ACTIVITY_ASSIGN,
      DP.DEPARTMENT_MEETING_VIEW,
      DP.DEPARTMENT_ACTION_VIEW,
      DP.DEPARTMENT_ACTION_UPDATE,
      DP.DEPARTMENT_QUALITY_VIEW,
      DP.DEPARTMENT_COMPLIANCE_VIEW,
      DP.DEPARTMENT_ACCREDITATION_VIEW,
      DP.DEPARTMENT_IMPROVEMENT_VIEW,
      DP.DEPARTMENT_NOTIFICATION_SEND,
    ],
  },
  [ROLES.IQAC_COORDINATOR]: {
    label: 'IQAC Coordinator',
    modules: ['dashboard', 'staff', 'review', 'evidence', 'activities', 'meetings', 'actions', 'quality', 'compliance', 'accreditation', 'improvement', 'notifications'],
    permissions: [
      DP.DEPARTMENT_DASHBOARD_VIEW,
      DP.DEPARTMENT_STAFF_VIEW,
      DP.DEPARTMENT_STAFF_DETAILS_VIEW,
      DP.DEPARTMENT_SUBMISSION_VIEW,
      DP.DEPARTMENT_SUBMISSION_REVIEW,
      DP.DEPARTMENT_SUBMISSION_APPROVE,
      DP.DEPARTMENT_SUBMISSION_RETURN,
      DP.DEPARTMENT_SUBMISSION_REJECT,
      DP.DEPARTMENT_SUBMISSION_COMMENT,
      DP.DEPARTMENT_EVIDENCE_VIEW,
      DP.DEPARTMENT_EVIDENCE_REVIEW,
      DP.DEPARTMENT_EVIDENCE_RETURN,
      DP.DEPARTMENT_EVIDENCE_COMMENT,
      DP.DEPARTMENT_ACTIVITY_VIEW,
      DP.DEPARTMENT_ACTIVITY_CREATE,
      DP.DEPARTMENT_ACTIVITY_EDIT,
      DP.DEPARTMENT_ACTIVITY_ASSIGN,
      DP.DEPARTMENT_MEETING_VIEW,
      DP.DEPARTMENT_MEETING_CREATE,
      DP.DEPARTMENT_MEETING_EDIT,
      DP.DEPARTMENT_MEETING_MANAGE_AGENDA,
      DP.DEPARTMENT_MEETING_MANAGE_MINUTES,
      DP.DEPARTMENT_ACTION_VIEW,
      DP.DEPARTMENT_ACTION_ASSIGN,
      DP.DEPARTMENT_ACTION_UPDATE,
      DP.DEPARTMENT_QUALITY_VIEW,
      DP.DEPARTMENT_COMPLIANCE_VIEW,
      DP.DEPARTMENT_COMPLIANCE_UPDATE,
      DP.DEPARTMENT_ACCREDITATION_VIEW,
      DP.DEPARTMENT_ACCREDITATION_UPDATE,
      DP.DEPARTMENT_IMPROVEMENT_VIEW,
      DP.DEPARTMENT_IMPROVEMENT_UPDATE,
      DP.DEPARTMENT_NOTIFICATION_SEND,
    ],
  },
};

export const DEPARTMENT_ROLES = [ROLES.HOD, ROLES.IQAC_COORDINATOR];

export const isDepartmentRole = (role) => DEPARTMENT_ROLES.includes(role);

// Central permission check for department portal UI. Grants access when the
// user carries the DEPARTMENT_* permission, the institutional fallback, or
// the role baseline in DEPARTMENT_PORTAL_CONFIG.
export const hasDepartmentPermission = (user, permission) => {
  if (!user || !permission) return false;
  const userPermissions = user.permissions || [];
  if (userPermissions.includes(permission)) return true;
  const fallback = DEPARTMENT_PERMISSION_FALLBACK[permission];
  if (fallback && userPermissions.includes(fallback)) return true;
  const roleConfig = DEPARTMENT_PORTAL_CONFIG[user.role];
  if (roleConfig && roleConfig.permissions.includes(permission)) return true;
  return false;
};

// Permission-filtered sidebar modules for the current user.
export const getModulesForUser = (user) => {
  if (!user) return [];
  const roleConfig = DEPARTMENT_PORTAL_CONFIG[user.role];
  const allowedIds = roleConfig ? roleConfig.modules : DEPARTMENT_MODULES.map((m) => m.id);
  return DEPARTMENT_MODULES.filter(
    (m) => allowedIds.includes(m.id) && hasDepartmentPermission(user, m.permission),
  );
};

export const getRoleLabel = (role) => {
  if (role === ROLES.HOD) return 'HOD';
  if (role === ROLES.IQAC_COORDINATOR) return 'IQAC Coordinator';
  return role || 'Department User';
};
