// Institutional RBAC Permissions

export const PERMISSIONS = {
  // Stage 1 & 2 permissions
  VIEW_INSTITUTION: 'VIEW_INSTITUTION',
  VIEW_ALL_DEPARTMENTS: 'VIEW_ALL_DEPARTMENTS',
  VIEW_ALL_ANALYTICS: 'VIEW_ALL_ANALYTICS',
  VIEW_ACADEMIC_ANALYTICS: 'VIEW_ACADEMIC_ANALYTICS',
  VIEW_STUDENT_ANALYTICS: 'VIEW_STUDENT_ANALYTICS',
  VIEW_FACULTY_ANALYTICS: 'VIEW_FACULTY_ANALYTICS',
  VIEW_RESEARCH_ANALYTICS: 'VIEW_RESEARCH_ANALYTICS',
  VIEW_PUBLICATION_ANALYTICS: 'VIEW_PUBLICATION_ANALYTICS',
  VIEW_PLACEMENT_ANALYTICS: 'VIEW_PLACEMENT_ANALYTICS',
  VIEW_MANAGEMENT_INSIGHTS: 'VIEW_MANAGEMENT_INSIGHTS',
  VIEW_PERFORMANCE_ALERTS: 'VIEW_PERFORMANCE_ALERTS',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',

  // Stage 4 Report Management Permissions
  VIEW_ALL_REPORTS: 'VIEW_ALL_REPORTS',
  GENERATE_ALL_REPORTS: 'GENERATE_ALL_REPORTS',
  DOWNLOAD_ALL_REPORTS: 'DOWNLOAD_ALL_REPORTS',
  ARCHIVE_REPORTS: 'ARCHIVE_REPORTS',
  VIEW_REPORT_HISTORY: 'VIEW_REPORT_HISTORY',
  VIEW_INSTITUTION_REPORTS: 'VIEW_INSTITUTION_REPORTS',
  GENERATE_INSTITUTION_REPORTS: 'GENERATE_INSTITUTION_REPORTS',
  VIEW_DEPARTMENT_REPORTS: 'VIEW_DEPARTMENT_REPORTS',
  GENERATE_DEPARTMENT_REPORTS: 'GENERATE_DEPARTMENT_REPORTS',
  DOWNLOAD_REPORTS: 'DOWNLOAD_REPORTS',
  VIEW_REPORTS: 'VIEW_REPORTS',

  // Architectural reservation for future Principal authority
  MANAGE_IQAC_HEAD: 'MANAGE_IQAC_HEAD',
};

// Permissions specific to Technical Director (Highest Command Authority)
export const TECHNICAL_DIRECTOR_PERMISSIONS = [
  PERMISSIONS.VIEW_INSTITUTION,
  PERMISSIONS.VIEW_ALL_DEPARTMENTS,
  PERMISSIONS.VIEW_ALL_ANALYTICS,
  PERMISSIONS.VIEW_ACADEMIC_ANALYTICS,
  PERMISSIONS.VIEW_STUDENT_ANALYTICS,
  PERMISSIONS.VIEW_FACULTY_ANALYTICS,
  PERMISSIONS.VIEW_RESEARCH_ANALYTICS,
  PERMISSIONS.VIEW_PUBLICATION_ANALYTICS,
  PERMISSIONS.VIEW_PLACEMENT_ANALYTICS,
  PERMISSIONS.VIEW_MANAGEMENT_INSIGHTS,
  PERMISSIONS.VIEW_PERFORMANCE_ALERTS,
  PERMISSIONS.VIEW_AUDIT_LOGS,
  PERMISSIONS.VIEW_REPORTS,
  PERMISSIONS.VIEW_ALL_REPORTS,
  PERMISSIONS.GENERATE_ALL_REPORTS,
  PERMISSIONS.DOWNLOAD_ALL_REPORTS,
  PERMISSIONS.ARCHIVE_REPORTS,
  PERMISSIONS.VIEW_REPORT_HISTORY,
  PERMISSIONS.VIEW_INSTITUTION_REPORTS,
  PERMISSIONS.GENERATE_INSTITUTION_REPORTS,
  PERMISSIONS.VIEW_DEPARTMENT_REPORTS,
  PERMISSIONS.GENERATE_DEPARTMENT_REPORTS,
  PERMISSIONS.DOWNLOAD_REPORTS,
];

// Permissions specific to Executive Director / Principal
export const EXECUTIVE_DIRECTOR_PERMISSIONS = [
  PERMISSIONS.VIEW_INSTITUTION,
  PERMISSIONS.VIEW_ALL_DEPARTMENTS,
  PERMISSIONS.VIEW_ALL_ANALYTICS,
  PERMISSIONS.VIEW_ACADEMIC_ANALYTICS,
  PERMISSIONS.VIEW_STUDENT_ANALYTICS,
  PERMISSIONS.VIEW_FACULTY_ANALYTICS,
  PERMISSIONS.VIEW_RESEARCH_ANALYTICS,
  PERMISSIONS.VIEW_PUBLICATION_ANALYTICS,
  PERMISSIONS.VIEW_PLACEMENT_ANALYTICS,
  PERMISSIONS.VIEW_MANAGEMENT_INSIGHTS,
  PERMISSIONS.VIEW_PERFORMANCE_ALERTS,
  PERMISSIONS.VIEW_REPORTS,
  PERMISSIONS.VIEW_INSTITUTION_REPORTS,
  PERMISSIONS.GENERATE_INSTITUTION_REPORTS,
  PERMISSIONS.VIEW_DEPARTMENT_REPORTS,
  PERMISSIONS.GENERATE_DEPARTMENT_REPORTS,
  PERMISSIONS.DOWNLOAD_REPORTS,
  PERMISSIONS.VIEW_REPORT_HISTORY,
];

export const ROLE_PERMISSIONS = {
  INSTITUTION_ADMIN: TECHNICAL_DIRECTOR_PERMISSIONS,
  IQAC_HEAD: [
    PERMISSIONS.VIEW_INSTITUTION,
    PERMISSIONS.VIEW_ALL_DEPARTMENTS,
    PERMISSIONS.VIEW_ALL_ANALYTICS,
    PERMISSIONS.VIEW_ACADEMIC_ANALYTICS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_INSTITUTION_REPORTS,
    PERMISSIONS.GENERATE_INSTITUTION_REPORTS,
    PERMISSIONS.VIEW_REPORT_HISTORY,
    PERMISSIONS.DOWNLOAD_REPORTS,
  ],
  IQAC_MEMBER: [
    PERMISSIONS.VIEW_INSTITUTION,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_INSTITUTION_REPORTS,
  ],
  DEAN: [
    PERMISSIONS.VIEW_INSTITUTION,
    PERMISSIONS.VIEW_ALL_ANALYTICS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_INSTITUTION_REPORTS,
    PERMISSIONS.DOWNLOAD_REPORTS,
  ],
  HOD: [
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_DEPARTMENT_REPORTS,
    PERMISSIONS.GENERATE_DEPARTMENT_REPORTS,
    PERMISSIONS.DOWNLOAD_REPORTS,
  ],
  STAFF: [
    PERMISSIONS.VIEW_REPORTS,
  ],
};
