import { ROLES } from './roles';

// Granular permission keys
export const PERMISSIONS = {
  // Profile & Basic
  VIEW_OWN_PROFILE: 'VIEW_OWN_PROFILE',
  EDIT_OWN_PROFILE: 'EDIT_OWN_PROFILE',

  // Academic Information
  VIEW_ACADEMIC_INFO: 'VIEW_ACADEMIC_INFO',
  CREATE_ACADEMIC_INFO: 'CREATE_ACADEMIC_INFO',
  EDIT_ACADEMIC_INFO: 'EDIT_ACADEMIC_INFO',
  DELETE_ACADEMIC_INFO: 'DELETE_ACADEMIC_INFO',

  // Publications
  VIEW_PUBLICATIONS: 'VIEW_PUBLICATIONS',
  CREATE_PUBLICATION: 'CREATE_PUBLICATION',
  EDIT_PUBLICATION: 'EDIT_PUBLICATION',
  DELETE_PUBLICATION: 'DELETE_PUBLICATION',
  SUBMIT_PUBLICATION: 'SUBMIT_PUBLICATION',

  // Research Projects & Grants
  VIEW_RESEARCH: 'VIEW_RESEARCH',
  CREATE_RESEARCH: 'CREATE_RESEARCH',
  EDIT_RESEARCH: 'EDIT_RESEARCH',
  DELETE_RESEARCH: 'DELETE_RESEARCH',
  SUBMIT_RESEARCH: 'SUBMIT_RESEARCH',

  // FDP & Training
  VIEW_FDP: 'VIEW_FDP',
  CREATE_FDP: 'CREATE_FDP',
  EDIT_FDP: 'EDIT_FDP',
  DELETE_FDP: 'DELETE_FDP',

  // Student Achievements
  VIEW_ACHIEVEMENTS: 'VIEW_ACHIEVEMENTS',
  CREATE_ACHIEVEMENTS: 'CREATE_ACHIEVEMENTS',
  EDIT_ACHIEVEMENTS: 'EDIT_ACHIEVEMENTS',
  DELETE_ACHIEVEMENTS: 'DELETE_ACHIEVEMENTS',

  // Documents
  VIEW_DOCUMENTS: 'VIEW_DOCUMENTS',
  UPLOAD_DOCUMENT: 'UPLOAD_DOCUMENT',
  DELETE_DOCUMENT: 'DELETE_DOCUMENT',

  // Department Level (HOD)
  VIEW_DEPARTMENT_DATA: 'VIEW_DEPARTMENT_DATA',
  MANAGE_DEPARTMENT_FACULTY: 'MANAGE_DEPARTMENT_FACULTY',
  APPROVE_STAFF_SUBMISSIONS: 'APPROVE_STAFF_SUBMISSIONS',
  VIEW_DEPARTMENT_ANALYTICS: 'VIEW_DEPARTMENT_ANALYTICS',

  // Dean Level
  VIEW_DEAN_ANALYTICS: 'VIEW_DEAN_ANALYTICS',

  // IQAC Member Level
  VERIFY_EVIDENCE: 'VERIFY_EVIDENCE',
  VIEW_AUDITS: 'VIEW_AUDITS',

  // IQAC Head Level (Institutional Control)
  VIEW_COLLEGE_DATA: 'VIEW_COLLEGE_DATA',
  APPROVE_HOD: 'APPROVE_HOD',
  APPROVE_DEAN: 'APPROVE_DEAN',
  APPROVE_IQAC_MEMBER: 'APPROVE_IQAC_MEMBER',
  MANAGE_QUALITY_INITIATIVES: 'MANAGE_QUALITY_INITIATIVES',
  MANAGE_AUDITS: 'MANAGE_AUDITS',
  MANAGE_ACCREDITATION: 'MANAGE_ACCREDITATION',
  COMPARE_DEPARTMENTS: 'COMPARE_DEPARTMENTS',

  // Director Level
  VIEW_INSTITUTION_OVERVIEW: 'VIEW_INSTITUTION_OVERVIEW',
  VIEW_INSTITUTION_ANALYTICS: 'VIEW_INSTITUTION_ANALYTICS',
  MANAGE_IQAC_HEAD: 'MANAGE_IQAC_HEAD', // Specific permission for designated director

  // Reports
  GENERATE_PERSONAL_REPORTS: 'GENERATE_PERSONAL_REPORTS',
  GENERATE_DEPARTMENT_REPORTS: 'GENERATE_DEPARTMENT_REPORTS',
  GENERATE_INSTITUTION_REPORTS: 'GENERATE_INSTITUTION_REPORTS',
};

// Default role to permission mappings
export const ROLE_PERMISSIONS = {
  [ROLES.STAFF]: [
    PERMISSIONS.VIEW_OWN_PROFILE,
    PERMISSIONS.EDIT_OWN_PROFILE,
    PERMISSIONS.VIEW_ACADEMIC_INFO,
    PERMISSIONS.CREATE_ACADEMIC_INFO,
    PERMISSIONS.EDIT_ACADEMIC_INFO,
    PERMISSIONS.DELETE_ACADEMIC_INFO,
    PERMISSIONS.VIEW_PUBLICATIONS,
    PERMISSIONS.CREATE_PUBLICATION,
    PERMISSIONS.EDIT_PUBLICATION,
    PERMISSIONS.DELETE_PUBLICATION,
    PERMISSIONS.SUBMIT_PUBLICATION,
    PERMISSIONS.VIEW_RESEARCH,
    PERMISSIONS.CREATE_RESEARCH,
    PERMISSIONS.EDIT_RESEARCH,
    PERMISSIONS.DELETE_RESEARCH,
    PERMISSIONS.SUBMIT_RESEARCH,
    PERMISSIONS.VIEW_FDP,
    PERMISSIONS.CREATE_FDP,
    PERMISSIONS.EDIT_FDP,
    PERMISSIONS.DELETE_FDP,
    PERMISSIONS.VIEW_ACHIEVEMENTS,
    PERMISSIONS.CREATE_ACHIEVEMENTS,
    PERMISSIONS.EDIT_ACHIEVEMENTS,
    PERMISSIONS.DELETE_ACHIEVEMENTS,
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.UPLOAD_DOCUMENT,
    PERMISSIONS.DELETE_DOCUMENT,
    PERMISSIONS.GENERATE_PERSONAL_REPORTS,
  ],

  [ROLES.HOD]: [
    PERMISSIONS.VIEW_OWN_PROFILE,
    PERMISSIONS.EDIT_OWN_PROFILE,
    PERMISSIONS.VIEW_DEPARTMENT_DATA,
    PERMISSIONS.MANAGE_DEPARTMENT_FACULTY,
    PERMISSIONS.APPROVE_STAFF_SUBMISSIONS,
    PERMISSIONS.VIEW_DEPARTMENT_ANALYTICS,
    PERMISSIONS.VIEW_PUBLICATIONS,
    PERMISSIONS.VIEW_RESEARCH,
    PERMISSIONS.VIEW_FDP,
    PERMISSIONS.VIEW_ACHIEVEMENTS,
    PERMISSIONS.VIEW_ACADEMIC_INFO,
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.UPLOAD_DOCUMENT,
    PERMISSIONS.GENERATE_PERSONAL_REPORTS,
    PERMISSIONS.GENERATE_DEPARTMENT_REPORTS,
  ],

  [ROLES.DEAN]: [
    PERMISSIONS.VIEW_OWN_PROFILE,
    PERMISSIONS.EDIT_OWN_PROFILE,
    PERMISSIONS.VIEW_COLLEGE_DATA,
    PERMISSIONS.VIEW_DEAN_ANALYTICS,
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.GENERATE_INSTITUTION_REPORTS,
  ],

  [ROLES.IQAC_MEMBER]: [
    PERMISSIONS.VIEW_OWN_PROFILE,
    PERMISSIONS.EDIT_OWN_PROFILE,
    PERMISSIONS.VIEW_COLLEGE_DATA,
    PERMISSIONS.VERIFY_EVIDENCE,
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.VIEW_AUDITS,
    PERMISSIONS.COMPARE_DEPARTMENTS,
    PERMISSIONS.GENERATE_INSTITUTION_REPORTS,
  ],

  [ROLES.IQAC_HEAD]: [
    PERMISSIONS.VIEW_OWN_PROFILE,
    PERMISSIONS.EDIT_OWN_PROFILE,
    PERMISSIONS.VIEW_COLLEGE_DATA,
    PERMISSIONS.APPROVE_HOD,
    PERMISSIONS.APPROVE_DEAN,
    PERMISSIONS.APPROVE_IQAC_MEMBER,
    PERMISSIONS.VERIFY_EVIDENCE,
    PERMISSIONS.MANAGE_QUALITY_INITIATIVES,
    PERMISSIONS.MANAGE_AUDITS,
    PERMISSIONS.MANAGE_ACCREDITATION,
    PERMISSIONS.COMPARE_DEPARTMENTS,
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.UPLOAD_DOCUMENT,
    PERMISSIONS.DELETE_DOCUMENT,
    PERMISSIONS.GENERATE_INSTITUTION_REPORTS,
  ],

  [ROLES.DIRECTOR]: [
    PERMISSIONS.VIEW_OWN_PROFILE,
    PERMISSIONS.VIEW_INSTITUTION_OVERVIEW,
    PERMISSIONS.VIEW_INSTITUTION_ANALYTICS,
    PERMISSIONS.VIEW_COLLEGE_DATA,
    PERMISSIONS.COMPARE_DEPARTMENTS,
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.GENERATE_INSTITUTION_REPORTS,
  ],
};
