// Centralized Quality Indicator Configuration (Stage 5F)

export const QUALITY_INDICATOR_CATEGORIES = {
  ACADEMIC: 'ACADEMIC',
  FACULTY: 'FACULTY',
  STUDENT: 'STUDENT',
  RESEARCH: 'RESEARCH',
  PUBLICATION: 'PUBLICATION',
  INNOVATION: 'INNOVATION',
  PLACEMENT: 'PLACEMENT',
  FEEDBACK: 'FEEDBACK',
  EVIDENCE: 'EVIDENCE',
  COMPLIANCE: 'COMPLIANCE',
  IQAC_OPERATION: 'IQAC_OPERATION',
};

export const QUALITY_INDICATOR_CATEGORY_LABELS = {
  ACADEMIC: 'Academic Quality & Curriculum',
  FACULTY: 'Faculty Qualification & Excellence',
  STUDENT: 'Student Progression & Performance',
  RESEARCH: 'Research & Funded Grants',
  PUBLICATION: 'Scopus / SCI Journal Publications',
  INNOVATION: 'Patents & Intellectual Property',
  PLACEMENT: 'Placement & Higher Education',
  FEEDBACK: 'Stakeholder Feedback Collection',
  EVIDENCE: 'Supporting Evidence Completeness',
  COMPLIANCE: 'Institutional Compliance Rate',
  IQAC_OPERATION: 'IQAC Operations & Action Closure',
};

export const INDICATOR_STATUS = {
  EXCELLENT: 'EXCELLENT',
  GOOD: 'GOOD',
  SATISFACTORY: 'SATISFACTORY',
  WARNING: 'WARNING',
  CRITICAL: 'CRITICAL',
  NOT_AVAILABLE: 'NOT_AVAILABLE',
};

export const INDICATOR_STATUS_CONFIG = {
  EXCELLENT: {
    label: 'EXCELLENT',
    classes: 'bg-emerald-50 text-emerald-800 border-emerald-300 font-extrabold shadow-2xs',
    dot: 'bg-emerald-500',
  },
  GOOD: {
    label: 'GOOD',
    classes: 'bg-teal-50 text-teal-800 border-teal-200 font-bold',
    dot: 'bg-teal-500',
  },
  SATISFACTORY: {
    label: 'SATISFACTORY',
    classes: 'bg-blue-50 text-blue-800 border-blue-200 font-bold',
    dot: 'bg-blue-500',
  },
  WARNING: {
    label: 'WARNING / NEEDS ATTENTION',
    classes: 'bg-amber-50 text-amber-800 border-amber-200 font-bold',
    dot: 'bg-amber-500',
  },
  CRITICAL: {
    label: 'CRITICAL ATTENTION',
    classes: 'bg-rose-50 text-rose-800 border-rose-300 font-extrabold shadow-2xs',
    dot: 'bg-rose-500',
  },
  NOT_AVAILABLE: {
    label: 'N/A',
    classes: 'bg-slate-100 text-slate-600 border-slate-200',
    dot: 'bg-slate-400',
  },
};

export const QUALITY_INDICATOR_DEFINITIONS = [
  {
    id: 'FACULTY_QUALIFICATION_RATE',
    code: 'QI-001',
    name: 'Faculty Ph.D. Qualification Rate',
    description: 'Percentage of full-time faculty holding Ph.D. qualifications.',
    category: QUALITY_INDICATOR_CATEGORIES.FACULTY,
    unit: 'PERCENTAGE',
    target: 85,
    warningThreshold: 70,
    criticalThreshold: 55,
    direction: 'HIGHER_IS_BETTER',
    frequency: 'ANNUAL',
    applicableScopes: ['INSTITUTION', 'DEPARTMENT'],
    dataSource: 'FACULTY_PROFILE',
    enabled: true,
  },
  {
    id: 'FDP_PARTICIPATION_RATE',
    code: 'QI-002',
    name: 'Faculty FDP Training Rate',
    description: 'Percentage of faculty completing at least one 5-day ATAL/NPTEL FDP annually.',
    category: QUALITY_INDICATOR_CATEGORIES.FACULTY,
    unit: 'PERCENTAGE',
    target: 90,
    warningThreshold: 75,
    criticalThreshold: 60,
    direction: 'HIGHER_IS_BETTER',
    frequency: 'ANNUAL',
    applicableScopes: ['INSTITUTION', 'DEPARTMENT'],
    dataSource: 'FDP_TRAINING',
    enabled: true,
  },
  {
    id: 'SCOPUS_PUBLICATION_RATE',
    code: 'QI-003',
    name: 'Scopus / SCI Publication Output Rate',
    description: 'Average Scopus/SCI indexed publications per faculty member per year.',
    category: QUALITY_INDICATOR_CATEGORIES.PUBLICATION,
    unit: 'RATIO',
    target: 1.5,
    warningThreshold: 1.0,
    criticalThreshold: 0.5,
    direction: 'HIGHER_IS_BETTER',
    frequency: 'ANNUAL',
    applicableScopes: ['INSTITUTION', 'DEPARTMENT'],
    dataSource: 'PUBLICATION',
    enabled: true,
  },
  {
    id: 'EVIDENCE_VERIFICATION_RATE',
    code: 'QI-004',
    name: 'Evidence Verification Completeness',
    description: 'Percentage of submitted supporting evidence documents officially verified by IQAC.',
    category: QUALITY_INDICATOR_CATEGORIES.EVIDENCE,
    unit: 'PERCENTAGE',
    target: 95,
    warningThreshold: 80,
    criticalThreshold: 65,
    direction: 'HIGHER_IS_BETTER',
    frequency: 'CONTINUOUS',
    applicableScopes: ['INSTITUTION', 'DEPARTMENT'],
    dataSource: 'EVIDENCE_REPOSITORY',
    enabled: true,
  },
  {
    id: 'ACTION_ITEM_CLOSURE_RATE',
    code: 'QI-005',
    name: 'IQAC Resolution Action Item Closure',
    description: 'Percentage of meeting resolution action items completed before target due date.',
    category: QUALITY_INDICATOR_CATEGORIES.IQAC_OPERATION,
    unit: 'PERCENTAGE',
    target: 90,
    warningThreshold: 75,
    criticalThreshold: 60,
    direction: 'HIGHER_IS_BETTER',
    frequency: 'QUARTERLY',
    applicableScopes: ['INSTITUTION', 'DEPARTMENT'],
    dataSource: 'ACTION_ITEMS',
    enabled: true,
  },
  {
    id: 'STUDENT_FEEDBACK_RATE',
    code: 'QI-006',
    name: 'Student Feedback Completion & Rating',
    description: 'Average student feedback completion and overall satisfaction rating.',
    category: QUALITY_INDICATOR_CATEGORIES.FEEDBACK,
    unit: 'PERCENTAGE',
    target: 88,
    warningThreshold: 75,
    criticalThreshold: 60,
    direction: 'HIGHER_IS_BETTER',
    frequency: 'SEMESTER',
    applicableScopes: ['INSTITUTION', 'DEPARTMENT'],
    dataSource: 'FEEDBACK',
    enabled: true,
  },
];
