// Central Configuration for Report Management & Generation System

export const REPORT_CATEGORIES = [
  { id: 'ALL', name: 'All Categories' },
  { id: 'INSTITUTIONAL', name: 'Institutional', icon: 'Building2', color: 'indigo' },
  { id: 'ACADEMIC', name: 'Academic', icon: 'GraduationCap', color: 'emerald' },
  { id: 'RESEARCH', name: 'Research & IPR', icon: 'BookOpen', color: 'purple' },
  { id: 'PLACEMENT', name: 'Placement & Career', icon: 'Briefcase', color: 'blue' },
  { id: 'FACULTY', name: 'Faculty & HR', icon: 'Users', color: 'amber' },
  { id: 'STUDENT', name: 'Student Affairs', icon: 'Award', color: 'pink' },
  { id: 'IQAC', name: 'IQAC & Quality', icon: 'ShieldCheck', color: 'rose' },
];

export const REPORT_CONFIGS = [
  // --- 1. Institutional Category ---
  {
    id: 'annual-institutional-report',
    category: 'INSTITUTIONAL',
    name: 'Annual Institutional Comprehensive Report',
    description: 'Complete high-level institutional dossier covering academics, research, placements, infrastructure, and governance.',
    icon: 'Building2',
    color: 'indigo',
    availableFormats: ['PDF', 'Excel'],
    allowedScopes: ['INSTITUTION'],
    filters: ['academicYear'],
    isPopular: true,
    sections: [
      'executiveSummary',
      'institutionalProfile',
      'keyStatistics',
      'academicSummary',
      'facultyCapital',
      'researchInnovation',
      'placementsCareer',
      'departmentMatrix',
      'iqacQualityAudits',
      'keyObservations',
    ],
  },
  {
    id: 'institutional-overview',
    category: 'INSTITUTIONAL',
    name: 'Institutional Overview Report',
    description: 'Executive snapshot of overall campus operations, student strength, faculty ratio, and administrative benchmarks.',
    icon: 'Building2',
    color: 'indigo',
    availableFormats: ['PDF', 'Excel'],
    allowedScopes: ['INSTITUTION'],
    filters: ['academicYear'],
    isPopular: false,
    sections: ['executiveSummary', 'institutionalProfile', 'keyStatistics', 'departmentMatrix', 'keyObservations'],
  },
  {
    id: 'institutional-performance',
    category: 'INSTITUTIONAL',
    name: 'Institutional Quality & Performance Benchmark',
    description: '6-pillar multidimensional quality scorecard benchmarking all academic departments against institutional standards.',
    icon: 'Sparkles',
    color: 'indigo',
    availableFormats: ['PDF', 'Excel'],
    allowedScopes: ['INSTITUTION'],
    filters: ['academicYear'],
    isPopular: true,
    sections: ['executiveSummary', 'departmentScorecards', 'benchmarkComparison', 'performanceAlerts', 'keyObservations'],
  },

  // --- 2. Academic Category ---
  {
    id: 'academic-performance',
    category: 'ACADEMIC',
    name: 'Academic Performance & Examination Report',
    description: 'Autonomous semester examination pass percentages, grade distributions, distinction rates, and arrears analysis.',
    icon: 'GraduationCap',
    color: 'emerald',
    availableFormats: ['PDF', 'Excel'],
    allowedScopes: ['INSTITUTION', 'DEPARTMENT'],
    filters: ['academicYear', 'department', 'semester', 'program'],
    isPopular: true,
    sections: ['academicSummary', 'semesterPerformance', 'departmentAcademicTable', 'distinctionAnalysis', 'keyObservations'],
  },
  {
    id: 'department-academic',
    category: 'ACADEMIC',
    name: 'Department Academic Dossier',
    description: 'Detailed branch-level curriculum delivery, student pass rates, subject-wise analysis, and remedial actions.',
    icon: 'GraduationCap',
    color: 'emerald',
    availableFormats: ['PDF', 'Excel'],
    allowedScopes: ['DEPARTMENT'],
    filters: ['academicYear', 'department', 'semester'],
    isPopular: false,
    sections: ['departmentHeader', 'academicSummary', 'semesterPerformance', 'facultyTeachingLoad', 'keyObservations'],
  },
  {
    id: 'student-performance',
    category: 'ACADEMIC',
    name: 'Student Semester Progression Report',
    description: 'Comprehensive student progression, backlog clearance rates, and year-on-year academic growth indicators.',
    icon: 'Award',
    color: 'emerald',
    availableFormats: ['PDF', 'Excel'],
    allowedScopes: ['INSTITUTION', 'DEPARTMENT'],
    filters: ['academicYear', 'department', 'program'],
    isPopular: false,
    sections: ['studentProgression', 'backlogMatrix', 'performanceDistribution', 'keyObservations'],
  },

  // --- 3. Research & IPR Category ---
  {
    id: 'research-projects',
    category: 'RESEARCH',
    name: 'Sponsored Research & Grants Report',
    description: 'Extramural research grants mobilized from DST, SERB, AICTE, CSIR, and industry-sponsored research projects.',
    icon: 'BookOpen',
    color: 'purple',
    availableFormats: ['PDF', 'Excel'],
    allowedScopes: ['INSTITUTION', 'DEPARTMENT'],
    filters: ['academicYear', 'department', 'fundingAgency'],
    isPopular: true,
    sections: ['researchFundingSummary', 'sponsoredProjectsList', 'fundingAgencyBreakdown', 'consultancySummary', 'keyObservations'],
  },
  {
    id: 'publications-report',
    category: 'RESEARCH',
    name: 'Scopus & SCI Publications Dossier',
    description: 'Peer-reviewed scholarly output indexed in Scopus, Web of Science, and UGC-CARE with citation metrics.',
    icon: 'BookOpen',
    color: 'purple',
    availableFormats: ['PDF', 'Excel'],
    allowedScopes: ['INSTITUTION', 'DEPARTMENT'],
    filters: ['academicYear', 'department'],
    isPopular: true,
    sections: ['publicationSummary', 'indexingQualityBreakdown', 'departmentPublicationTable', 'topCitations', 'keyObservations'],
  },
  {
    id: 'patents-report',
    category: 'RESEARCH',
    name: 'IPR & Patents Commercialization Report',
    description: 'Institutional intellectual property filings, publications, formal government grants, and startup commercialization.',
    icon: 'Sparkles',
    color: 'purple',
    availableFormats: ['PDF', 'Excel'],
    allowedScopes: ['INSTITUTION', 'DEPARTMENT'],
    filters: ['academicYear', 'department'],
    isPopular: false,
    sections: ['patentsSummary', 'patentsStatusList', 'innovationStartups', 'keyObservations'],
  },

  // --- 4. Placement Category ---
  {
    id: 'placement-report',
    category: 'PLACEMENT',
    name: 'Campus Recruitment & Placement Dossier',
    description: 'Graduating batch placement percentages, total job offers, compensation CTC tiers, and recruiter statistics.',
    icon: 'Briefcase',
    color: 'blue',
    availableFormats: ['PDF', 'Excel'],
    allowedScopes: ['INSTITUTION', 'DEPARTMENT'],
    filters: ['academicYear', 'department', 'program'],
    isPopular: true,
    sections: ['placementSummary', 'packageDistributionTable', 'departmentPlacementTable', 'topRecruiters', 'keyObservations'],
  },
  {
    id: 'internship-report',
    category: 'PLACEMENT',
    name: 'Student Internships & Industrial Training Report',
    description: 'Pre-final and final year paid corporate internships, stipend benchmarks, and PPO conversion records.',
    icon: 'Briefcase',
    color: 'blue',
    availableFormats: ['PDF', 'Excel'],
    allowedScopes: ['INSTITUTION', 'DEPARTMENT'],
    filters: ['academicYear', 'department'],
    isPopular: false,
    sections: ['internshipSummary', 'industryPartners', 'ppoConversionTable', 'keyObservations'],
  },

  // --- 5. Faculty & HR Category ---
  {
    id: 'faculty-profile',
    category: 'FACULTY',
    name: 'Faculty Cadre & Qualification Profile',
    description: 'Human capital strength, cadre ratios (Prof/Assoc/Asst), doctorate attainment (Ph.D.), and industry immersion.',
    icon: 'Users',
    color: 'amber',
    availableFormats: ['PDF', 'Excel'],
    allowedScopes: ['INSTITUTION', 'DEPARTMENT'],
    filters: ['academicYear', 'department'],
    isPopular: false,
    sections: ['facultySummary', 'qualificationDistribution', 'cadreRatioTable', 'departmentFacultyList', 'keyObservations'],
  },
  {
    id: 'faculty-development',
    category: 'FACULTY',
    name: 'Faculty Development (FDP) Compliance Report',
    description: 'Pedagogical training hours, AICTE ATAL academy certifications, and international workshop participation.',
    icon: 'Users',
    color: 'amber',
    availableFormats: ['PDF', 'Excel'],
    allowedScopes: ['INSTITUTION', 'DEPARTMENT'],
    filters: ['academicYear', 'department', 'fdpType'],
    isPopular: true,
    sections: ['fdpComplianceSummary', 'trainingHoursTable', 'nbaComplianceStatus', 'keyObservations'],
  },

  // --- 6. Student Affairs Category ---
  {
    id: 'student-achievement',
    category: 'STUDENT',
    name: 'Student Accolades & Hackathons Report',
    description: 'National and international hackathons, paper awards, patent filings by students, and athletic achievements.',
    icon: 'Award',
    color: 'pink',
    availableFormats: ['PDF', 'Excel'],
    allowedScopes: ['INSTITUTION', 'DEPARTMENT'],
    filters: ['academicYear', 'department'],
    isPopular: false,
    sections: ['studentAchievementSummary', 'hackathonWinnersList', 'sportsArtsRecognitions', 'keyObservations'],
  },
  {
    id: 'student-progression',
    category: 'STUDENT',
    name: 'Student Progression & Higher Education Report',
    description: 'Graduate transition to premier domestic (GATE/CAT) and international universities for higher studies.',
    icon: 'GraduationCap',
    color: 'pink',
    availableFormats: ['PDF', 'Excel'],
    allowedScopes: ['INSTITUTION', 'DEPARTMENT'],
    filters: ['academicYear', 'department'],
    isPopular: false,
    sections: ['progressionFunnel', 'higherEducationList', 'competitiveExamsSummary', 'keyObservations'],
  },

  // --- 7. IQAC & Quality Assurance Category ---
  {
    id: 'iqac-annual-report',
    category: 'IQAC',
    name: 'IQAC Annual Quality Assurance Dossier (AQAR Preview)',
    description: 'Annual statutory quality audit compilation structured across NAAC 7-criteria quality benchmarks.',
    icon: 'ShieldCheck',
    color: 'rose',
    availableFormats: ['PDF', 'Excel'],
    allowedScopes: ['INSTITUTION'],
    filters: ['academicYear'],
    isPopular: true,
    sections: ['iqacOverview', 'sevenCriteriaSummary', 'bestPractices', 'actionTakenReport', 'keyObservations'],
  },
  {
    id: 'verification-status',
    category: 'IQAC',
    name: 'Institutional Data Verification & Audit Report',
    description: 'Departmental data submission timelines, HOD verifications, and central IQAC audit clearance audit trail.',
    icon: 'ShieldCheck',
    color: 'rose',
    availableFormats: ['PDF', 'Excel'],
    allowedScopes: ['INSTITUTION'],
    filters: ['academicYear'],
    isPopular: false,
    sections: ['auditTrailSummary', 'departmentSubmissionStatus', 'pendingVerifications', 'keyObservations'],
  },
];
