import React, { useState, useEffect } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { reportService } from '../../services/reportService';
import { ReportPreview } from '../../components/reports/ReportPreview';
import { Card } from '../../components/common/Card';
import { Button } from '../../components/common/Button';
import { Loader } from '../../components/common/Loader';
import { 
  ArrowLeft, 
  Printer, 
  Download, 
  FileSpreadsheet, 
  Share2, 
  Check, 
  AlertCircle 
} from 'lucide-react';

export const ReportDetails = () => {
  const { reportId } = useParams();
  const navigate = useNavigate();
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    const fetchReport = async () => {
      setLoading(true);
      setError(null);
      try {
        const res = await reportService.getReportById(reportId);
        if (res.success) {
          setReport(res.report);
        }
      } catch (err) {
        console.error('Error fetching report dossier:', err);
        setError(err.message || 'Unable to locate report dossier.');
      } finally {
        setLoading(false);
      }
    };
    fetchReport();
  }, [reportId]);

  if (loading) {
    return <Loader message={`Loading formal report dossier [${reportId}]...`} />;
  }

  if (error || !report) {
    return (
      <Card className="p-8 text-center space-y-4 max-w-md mx-auto my-12">
        <AlertCircle className="w-10 h-10 text-rose-600 mx-auto" />
        <div className="space-y-1">
          <h3 className="text-base font-bold text-slate-900">Report Not Found</h3>
          <p className="text-xs text-slate-500">{error || 'The requested dossier could not be retrieved.'}</p>
        </div>
        <Link to="/director/reports">
          <Button variant="primary" size="sm">
            Back to Report Center
          </Button>
        </Link>
      </Card>
    );
  }

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadCsv = () => {
    reportService.downloadReport(report, 'CSV');
  };

  const handleCopyLink = () => {
    navigator.clipboard.writeText(window.location.href);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-6">
      {/* Top Action Bar (Hidden during Print) */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-slate-200/80 print:hidden">
        <div className="flex items-center gap-2.5">
          <Link to="/director/reports/history">
            <Button variant="ghost" size="xs" icon={ArrowLeft}>
              Report History
            </Button>
          </Link>
          <div>
            <div className="flex items-center gap-2">
              <span className="font-mono text-xs font-bold text-indigo-700 bg-indigo-50 px-2 py-0.5 rounded border border-indigo-200">
                {report.id}
              </span>
              <h2 className="text-lg font-bold text-slate-900 tracking-tight">{report.title}</h2>
            </div>
            <p className="text-xs text-slate-500 font-medium">
              Academic Cycle: {report.academicYear} &bull; Generated by {report.generatedBy} on {report.generatedDate}
            </p>
          </div>
        </div>

        {/* Action Buttons Strip */}
        <div className="flex items-center gap-2 flex-wrap">
          <Button
            variant="ghost"
            size="sm"
            icon={copied ? Check : Share2}
            onClick={handleCopyLink}
            className="text-slate-700"
          >
            {copied ? 'Link Copied' : 'Share Link'}
          </Button>

          <Button
            variant="outline"
            size="sm"
            icon={FileSpreadsheet}
            onClick={handleDownloadCsv}
          >
            Export Excel / CSV
          </Button>

          <Button
            variant="primary"
            size="sm"
            icon={Printer}
            onClick={handlePrint}
          >
            Print / Save as PDF
          </Button>
        </div>
      </div>

      {/* Main Report Preview Container */}
      <ReportPreview report={report} />
    </div>
  );
};
