import React from 'react';
import { Link } from 'react-router-dom';
import { Card } from '../common/Card';
import { Badge } from '../common/Badge';
import { Button } from '../common/Button';
import { 
  Eye, 
  Download, 
  Printer, 
  Archive, 
  FileText, 
  Calendar, 
  User, 
  CheckCircle2, 
  ArchiveRestore 
} from 'lucide-react';
import { reportService } from '../../services/reportService';

export const ReportHistoryTable = ({
  history = [],
  onArchive = () => {},
  onDownload = (report) => reportService.downloadReport(report, 'CSV'),
}) => {
  if (!history || history.length === 0) {
    return (
      <Card className="p-8 text-center space-y-3">
        <div className="w-12 h-12 rounded-2xl bg-slate-100 text-slate-400 flex items-center justify-center mx-auto">
          <FileText className="w-6 h-6" />
        </div>
        <h4 className="text-sm font-bold text-slate-800">No Reports Generated Yet</h4>
        <p className="text-xs text-slate-500 max-w-sm mx-auto">
          Generated institutional dossiers and statutory audit reports will appear here in the historical ledger.
        </p>
        <Link to="/director/reports/generate">
          <Button variant="primary" size="sm" className="mt-2">
            Generate Your First Report
          </Button>
        </Link>
      </Card>
    );
  }

  const STATUS_STYLES = {
    GENERATED: 'bg-emerald-50 text-emerald-800 border-emerald-200',
    ARCHIVED: 'bg-slate-100 text-slate-600 border-slate-200',
    DRAFT: 'bg-amber-50 text-amber-800 border-amber-200',
  };

  return (
    <Card className="overflow-hidden border-slate-200/90 shadow-2xs">
      <div className="overflow-x-auto">
        <table className="w-full text-left border-collapse text-xs">
          <thead>
            <tr className="border-b border-slate-200 bg-slate-50 text-slate-600 font-bold uppercase text-[10px] tracking-wider">
              <th className="py-3 px-4">Report ID</th>
              <th className="py-3 px-4">Report Title & Scope</th>
              <th className="py-3 px-4">Category</th>
              <th className="py-3 px-4 text-center">Academic Year</th>
              <th className="py-3 px-4">Generated By</th>
              <th className="py-3 px-4">Generated Date</th>
              <th className="py-3 px-4 text-center">Status</th>
              <th className="py-3 px-4 text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100 font-medium">
            {history.map((rpt) => {
              const isArchived = rpt.status === 'ARCHIVED';
              return (
                <tr key={rpt.id} className="hover:bg-slate-50/80 transition group">
                  {/* Report ID */}
                  <td className="py-3 px-4">
                    <Link
                      to={`/director/reports/${rpt.id}`}
                      className="font-mono font-black text-indigo-600 hover:text-indigo-800 hover:underline"
                    >
                      {rpt.id}
                    </Link>
                  </td>

                  {/* Title & Scope */}
                  <td className="py-3 px-4">
                    <Link
                      to={`/director/reports/${rpt.id}`}
                      className="font-bold text-slate-900 group-hover:text-indigo-600 transition block truncate max-w-xs"
                    >
                      {rpt.title}
                    </Link>
                    <span className="text-[10px] text-slate-400 font-medium">
                      Scope: {rpt.scope === 'INSTITUTION' ? 'Institution-Wide' : `Dept: ${rpt.department}`}
                    </span>
                  </td>

                  {/* Category */}
                  <td className="py-3 px-4">
                    <span className="px-2 py-0.5 rounded text-[10px] font-extrabold uppercase bg-slate-100 text-slate-700">
                      {rpt.category}
                    </span>
                  </td>

                  {/* Academic Year */}
                  <td className="py-3 px-4 text-center">
                    <span className="font-mono font-bold text-slate-800 bg-indigo-50/70 border border-indigo-100 px-2 py-0.5 rounded text-[11px]">
                      {rpt.academicYear}
                    </span>
                  </td>

                  {/* Generated By */}
                  <td className="py-3 px-4">
                    <div className="font-bold text-slate-800 truncate">{rpt.generatedBy}</div>
                    <span className="text-[10px] text-slate-400 truncate block">
                      {rpt.generatedByRole}
                    </span>
                  </td>

                  {/* Generated Date */}
                  <td className="py-3 px-4 text-slate-600 text-[11px] whitespace-nowrap">
                    {rpt.generatedDate}
                  </td>

                  {/* Status */}
                  <td className="py-3 px-4 text-center">
                    <span
                      className={`px-2 py-0.5 rounded-full text-[10px] font-bold border ${
                        STATUS_STYLES[rpt.status] || STATUS_STYLES.GENERATED
                      }`}
                    >
                      {rpt.status}
                    </span>
                  </td>

                  {/* Actions */}
                  <td className="py-3 px-4 text-right">
                    <div className="flex items-center justify-end gap-1">
                      <Link to={`/director/reports/${rpt.id}`}>
                        <button
                          type="button"
                          title="View Report Dossier"
                          className="p-1.5 rounded-lg text-slate-500 hover:text-indigo-600 hover:bg-indigo-50 transition cursor-pointer"
                        >
                          <Eye className="w-3.5 h-3.5" />
                        </button>
                      </Link>

                      <button
                        type="button"
                        onClick={() => onDownload(rpt)}
                        title="Download CSV / Spreadsheet"
                        className="p-1.5 rounded-lg text-slate-500 hover:text-indigo-600 hover:bg-indigo-50 transition cursor-pointer"
                      >
                        <Download className="w-3.5 h-3.5" />
                      </button>

                      {!isArchived && (
                        <button
                          type="button"
                          onClick={() => onArchive(rpt.id)}
                          title="Archive Report"
                          className="p-1.5 rounded-lg text-slate-500 hover:text-rose-600 hover:bg-rose-50 transition cursor-pointer"
                        >
                          <Archive className="w-3.5 h-3.5" />
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </Card>
  );
};
